@startuml
title Logger Class Diagram
package eros {
    class Logger
    enum Logger::LoggerStatus
    enum Level::Type
    struct Diagnostic::DiagnosticDefinition
}
class Logger {
    +Logger(std::string level, std::string name)
    +Logger(std::string level, std::string directory, std::string name)
    +Level::Type get_logverbosity()
    +bool is_logger_ok()
    +bool set_logverbosity(Level::Type level)
    +void disable_consoleprint()
    +void enable_consoleprint()
    +bool enable_ROS_logger()

    +LoggerStatus log_debug(std::string str)
    +LoggerStatus log_info(std::string str)
    +LoggerStatus log_notice(std::string str)
    +LoggerStatus log_warn(std::string str)
    +LoggerStatus log_error(std::string str)
    +LoggerStatus log_fatal(std::string str)
    +LoggerStatus log_debug(std::string str)
    +LoggerStatus log_diagnostic(Diagnostic::DiagnosticDefinition diagnostic)   

}
enum Logger::LoggerStatus {
    FAILED_TO_OPEN
    LOG_WRITTEN
    LOG_SUPPRESSED
}
Logger +-- Logger::LoggerStatus
Level::Type *-- Logger
Diagnostic::DiagnosticDefinition *-- Logger
@enduml