@startuml
title Logger Class Diagram
package eros {
enum Logger::LoggerStatus

struct eros_diagnostic::Diagnostic
class Logger #Cyan {
    +Logger(std::string level, std::string name)
    +Logger(std::string level, std::string directory, std::string name)
    +Level::Type get_logverbosity()
    +bool is_logger_ok()
    +bool set_logverbosity(Level::Type level)
    +disable_consoleprint()
    +enable_consoleprint()
    +bool enable_ROS_logger()

    +LoggerStatus log_debug(std::string str)
    +LoggerStatus log_info(std::string str)
    +LoggerStatus log_notice(std::string str)
    +LoggerStatus log_warn(std::string str)
    +LoggerStatus log_error(std::string str)
    +LoggerStatus log_fatal(std::string str)
    +LoggerStatus log_debug(std::string str)
    +LoggerStatus log_diagnostic(eros_diagnostic::Diagnostic diagnostic)   

}
enum Level::Type #Cyan
enum Logger::LoggerStatus #Cyan {
    FAILED_TO_OPEN
    LOG_WRITTEN
    LOG_SUPPRESSED
}
Logger +-- Logger::LoggerStatus
Level::Type *-- Logger
eros_diagnostic::Diagnostic *-- Logger
}
@enduml