@startuml
title Resource Monitor Class Diagram
package eros {
   
    struct ResourceInfo
    class eros::loadfactor <<M,#FFFF00>>
    enum ResourceMonitor::Mode
    together {
        struct eros_diagnostic::Diagnostic
        class Logger
        enum Architecture::Type
    }
    ResourceMonitor +-- ResourceMonitor::Mode
    Logger *-- ResourceMonitor
    Architecture::Type *-- ResourceMonitor 
    eros_diagnostic::Diagnostic *-- ResourceMonitor 
    
    enum ResourceMonitor::Mode #LimeGreen {
        PROCESS
        DEVICE
    }
    class ResourceMonitor #LimeGreen {
        +ResourceMonitor(string name,Mode _mode, eros_diagnostic::Diagnostic _diag, Logger* _logger)
        +bool is_initialized()
        +std::string pretty(ResourceInfo info)
        +eros_diagnostic::Diagnostic init()
        +ResourceInfo get_resourceinfo()
        +Architecture::Type get_architecture()
        +eros_diagnostic::Diagnostic update(double t_dt)
        +eros::loadfactor get_load_factor()
        +bool reset()

    }
}
@enduml