@startuml
title System Monitor Utility Class Diagram
package curses {
    class WINDOW
}
package eros_nodes {
package SystemMonitor {
    struct ScreenCoordinatePixel
    class SystemMonitorUtility #LimeGreen {
        {static} WINDOW* create_newwin(int height, int width, int starty, int startx)
        {static} +ScreenCoordinatePixel create_newwin(int height, int width, int starty, int startx)
    }
}
}
@enduml