@startuml
title System Monitor Window Sequence Diagram
actor SystemMonitor as system_monitor
participant IWindow as interface
participant BaseWindow as base
participant ConcreteWindow as concrete

alt initialize
end

alt update
system_monitor -> interface++: update()
interface -> concrete++: update()
concrete -> base++: update()
base --> concrete--: diag
concrete -> concrete++: update_window()
concrete --> interface--: diag
interface --> system_monitor--: diag
end

@enduml