@startuml
title System Monitor Utilities Class Diagram
package curses {
    class WINDOW
}
package eros_nodes {
package SystemMonitor {
create_newwin(int height, int width, int starty, int startx)
}
}
@enduml