@startuml
title eROS Package Diagram
package eros #LimeGreen {
    class BaseNode #Cyan
    class BaseNodeProcess #Cyan
    
    class ResourceMonitor #Cyan
    struct ExecResult #Cyan
    struct Firmware #Cyan
    class FileHelper #LimeGreen
    class System #Cyan
    class Level #Cyan
    class ArmDisarm #LimeGreen
    class Command #Cyan
    class Node #Cyan
    class Architecture #Cyan
    class SnapshotState #Cyan
    namespace eros_diagnostic #LimeGreen {
        class Diagnostic #LimeGreen
        class DiagnosticManager #LimeGreen
    }
    namespace eros_utility {
        class CoreUtility #LimeGreen
        class ConvertUtility #LimeGreen
    }


}
package eros_nodes {
    class DataLoggerNode #Cyan
    class DataLoggerProcess #Cyan
    DataLoggerNode --> DataLoggerProcess
    class DiagnosticNode #Cyan
    class DiagnosticNodeProcess #Cyan
    DiagnosticNode --> DiagnosticNodeProcess
    class MasterNode #Cyan
    class MasterNodeProcess #Cyan
    MasterNode --> MasterNodeProcess
    class SafetyNode #Cyan
    class SafetyNodeProcess #Cyan
    SafetyNode --> SafetyNodeProcess
    class SnapshotNode #Cyan
    class SnapshotNodeProcess #Cyan
    SnapshotNode --> SnapshotNodeProcess
    class SystemMonitor #LimeGreen
    class SystemMonitorProcess #LimeGreen
    SystemMonitor --> SystemMonitorProcess
}
@enduml