@startuml
title Diagnostic Node Class Diagram
package eros {
    class BaseNode
    class BaseNodeProcess
}
namespace eros_nodes {
    class DiagnosticNode {
        -- Initialization Functions --

        -- Update Functions --

        -- Attribute Functions --

        -- Data Functions --

        -- Message Functions --

        -- Support Functions --

        -- Convert Functions --
        
        -- Printing Functions --

        -- Destructors --

        -- TODO --
    }
    class DiagnosticNodeProcess {
        -- Initialization Functions --

        -- Update Functions --

        -- Attribute Functions --

        -- Data Functions --

        -- Message Functions --

        -- Support Functions --

        -- Convert Functions --
        
        -- Printing Functions --

        -- Destructors --

        -- TODO --
    }

    BaseNode <|-- DiagnosticNode
    BaseNodeProcess <|-- DiagnosticNodeProcess
    DiagnosticNode -> DiagnosticNodeProcess 
}

@enduml