@startuml
enum CoordinateReference {

}
enum Color {
    RED
    GREEN
    BLUE
    WHITE
    BLACK
}
struct RenderCoordinate {
    +CoordinateReference reference
    +uint32_t x
    +uint32_t y
}
RenderCoordinate -* CoordinateReference
struct RenderData {
    +RenderCoordinate startCoordinate
    +Color color
    +string data

}
RenderData -* RenderCoordinate
RenderData -* Color
@enduml