#!/bin/bash
function print_usage()
{
    echo "Usage Instructions"
    echo "-r <path> Log data to path"
}

function log()
{
    echo "Logging to: "$1
	watch -n5 ps aux > $1"ps_log.txt" &
    watch -n5 top -bn1 > $1"top_log.txt" &
}


if [ $# -eq 0 ]; then
    print_usage
fi

if [ "$1" = "-r" ]; then
    log $2
fi
