%***************AUTO-GENERATED.  DO NOT EDIT********************/
%***Created on:%2019-11-03 16:30:44.922117%***/
global Message
Message.SYSTEMSTATE_ID = 0XAB46;
Message.CONTROLGROUPVALUE_ID = 0XAB45;
Message.SYSTEMSNAPSHOTSTATE_ID = 0XAB44;
Message.SUBSYSTEMDIAGNOSTIC_ID = 0XAB43;
Message.LEDSTRIPCONTROL_ID = 0XAB42;
Message.FIRMWARE_ID = 0XAB41;
Message.ID_ID = 0XAB40;
Message.TUNECONTROLGROUP_ID = 0XAB39;
Message.ESTOP_ID = 0XAB38;
Message.POWER_ID = 0XAB37;
Message.CONFIGURE_ANA_PORT_ID = 0XAB36;
Message.PPS_ID = 0XAB35;
Message.FINDTARGET_ID = 0XAB34;
Message.SET_DIO_PORT_DEFAULTVALUE_ID = 0XAB32;
Message.HEARTBEAT_ID = 0XAB31;
Message.ARM_STATUS_ID = 0XAB30;
Message.GET_IMUMAG_ID = 0XAB29;
Message.GET_IMUGYRO_ID = 0XAB28;
Message.GET_IMUACC_ID = 0XAB27;
Message.ARMCONTROL_ID = 0XAB26;
Message.FIRMWAREVERSION_ID = 0XAB25;
Message.GET_ANA_PORT2_ID = 0XAB21;
Message.GET_ANA_PORT1_ID = 0XAB20;
Message.GET_DIO_PORT1_ID = 0XAB19;
Message.SET_DIO_PORT_ID = 0XAB18;
Message.MODE_ID = 0XAB17;
Message.CONFIGURE_DIO_PORT_ID = 0XAB16;
Message.TESTMESSAGECOMMAND_ID = 0XAB15;
Message.TESTMESSAGECOUNTER_ID = 0XAB14;
Message.DEVICE_ID = 0XAB13;
Message.DIAGNOSTIC_ID = 0XAB12;
Message.RESOURCE_ID = 0XAB11;
Message.REMOTECONTROL_ID = 0XAB10;
Message.COMMAND_ID = 0XAB02;
Message.USERMESSAGE_ID = 0XAB01;


global System
System.ROVER = 1;
System.GROUND_STATION = 5;
System.REMOTE_CONTROL = 7;
System.SYSTEM_UNKNOWN = 255;


global Subsystem
Subsystem.ENTIRE_SYSTEM = 0;
Subsystem.ROBOT_CONTROLLER = 1;
Subsystem.ROBOT_MONITOR = 2;
Subsystem.SUBSYSTEM_UNKNOWN = 255;


global Component
Component.ENTIRE_SUBSYSTEM = 0;
Component.CONTROLLER_NODE = 1;
Component.DIAGNOSTIC_NODE = 2;
Component.NAVIGATION_NODE = 3;
Component.MAPPING_NODE = 7;
Component.EVOLUTION_NODE = 8;
Component.TARGETING_NODE = 9;
Component.TIMING_NODE = 10;
Component.VISION_NODE = 11;
Component.GPIO_NODE = 12;
Component.COMMUNICATION_NODE = 13;
Component.DYNAMICS_NODE = 14;
Component.POWER_NODE = 15;
Component.POSE_NODE = 16;
Component.COMPONENT_UNKNOWN = 255;


global DiagnosticType
DiagnosticType.ELECTRICAL = 1;
DiagnosticType.SOFTWARE = 2;
DiagnosticType.COMMUNICATIONS = 3;
DiagnosticType.SENSORS = 4;
DiagnosticType.ACTUATORS = 5;
DiagnosticType.DATA_STORAGE = 6;
DiagnosticType.REMOTE_CONTROL = 7;
DiagnosticType.TARGET_ACQUISITION = 8;
DiagnosticType.POSE = 9;
DiagnosticType.TIMING = 10;
DiagnosticType.SYSTEM_RESOURCE = 11;
DiagnosticType.GENERAL_ERROR = 255;


global DiagnosticLevel
DiagnosticLevel.DEBUG = 0;
DiagnosticLevel.INFO = 1;
DiagnosticLevel.NOTICE = 2;
DiagnosticLevel.WARN = 3;
DiagnosticLevel.ERROR = 4;
DiagnosticLevel.FATAL = 5;
DiagnosticLevel.LEVEL_UNKNOWN = 255;


global DiagnosticMessage
DiagnosticMessage.NOERROR = 0;
DiagnosticMessage.INITIALIZING = 1;
DiagnosticMessage.INITIALIZING_ERROR = 2;
DiagnosticMessage.DROPPING_PACKETS = 4;
DiagnosticMessage.MISSING_HEARTBEATS = 5;
DiagnosticMessage.DEVICE_NOT_AVAILABLE = 6;
DiagnosticMessage.ROVER_ARMED = 7;
DiagnosticMessage.ROVER_DISARMED = 8;
DiagnosticMessage.TEMPERATURE_HIGH = 9;
DiagnosticMessage.TEMPERATURE_LOW = 10;
DiagnosticMessage.DIAGNOSTIC_PASSED = 11;
DiagnosticMessage.DIAGNOSTIC_FAILED = 12;
DiagnosticMessage.RESOURCE_LEAK = 13;
DiagnosticMessage.HIGH_RESOURCE_USAGE = 14;
DiagnosticMessage.UNKNOWN_STATE = 15;
DiagnosticMessage.UNKNOWN_MESSAGE = 255;


global ArmedState
ArmedState.ARMEDSTATUS_UNDEFINED = 0;
ArmedState.ARMEDSTATUS_ARMED = 1;
ArmedState.ARMEDSTATUS_DISARMED_CANNOTARM = 2;
ArmedState.ARMEDSTATUS_DISARMED = 3;
ArmedState.ARMEDSTATUS_DISARMING = 4;
ArmedState.ARMEDSTATUS_ARMING = 5;


global BoardTypes
BoardTypes.BOARDTYPE_UNDEFINED = 0;
BoardTypes.BOARDTYPE_ARDUINOUNO = 1;
BoardTypes.BOARDTYPE_ARDUINOMEGA = 2;


global ShieldTypes
ShieldTypes.SHIELDTYPE_UNDEFINED = 0;
ShieldTypes.SHIELDTYPE_SERVOSHIELD = 1;
ShieldTypes.SHIELDTYPE_LCDSHIELD = 2;
ShieldTypes.SHIELDTYPE_RELAYSHIELD = 3;
ShieldTypes.SHIELDTYPE_TERMINALSHIELD = 4;
ShieldTypes.SHIELDTYPE_NONE = 255;


global HatTypes
HatTypes.HATTYPE_UNDEFINED = 0;
HatTypes.HATTYPE_TERMINALSHIELD = 1;
HatTypes.HATTYPE_SERVOHAT = 2;


global RoverCommands
RoverCommands.ROVERCOMMAND_UNDEFINED = 0;
RoverCommands.ROVERCOMMAND_BOOT = 1;
RoverCommands.ROVERCOMMAND_NONE = 2;
RoverCommands.ROVERCOMMAND_RUNDIAGNOSTIC = 3;
RoverCommands.ROVERCOMMAND_SEARCHFOR_RECHARGE_FACILITY = 4;
RoverCommands.ROVERCOMMAND_STOPSEARCHFOR_RECHARGE_FACILITY = 5;
RoverCommands.ROVERCOMMAND_ACQUIRE_TARGET = 6;
RoverCommands.ROVERCOMMAND_ARM = 7;
RoverCommands.ROVERCOMMAND_DISARM = 8;
RoverCommands.ROVERCOMMAND_CONFIGURE = 9;
RoverCommands.ROVERCOMMAND_RUN = 10;
RoverCommands.ROVERCOMMAND_STOPMOVEMENT = 11;
RoverCommands.ROVERCOMMAND_DRIVECOMMAND = 12;
RoverCommands.ROVERCOMMAND_RESET = 13;
RoverCommands.ROVERCOMMAND_SETLOGLEVEL = 14;
RoverCommands.ROVERCOMMAND_TASKCONTROL = 15;
RoverCommands.ROVERCOMMAND_CALIBRATION = 16;
RoverCommands.ROVERCOMMAND_GENERATESNAPSHOT = 17;
RoverCommands.ROVERCOMMAND_SIMULATIONCCONTROL = 18;
RoverCommands.ROVERCOMMAND_WAIT = 254;
RoverCommands.ROVERCOMMAND_UNKNOWN = 255;


global RoverStates
RoverStates.ROVERSTATE_UNDEFINED = 0;
RoverStates.ROVERSTATE_SIMULATION = 1;
RoverStates.ROVERSTATE_UNKNOWN = 255;


global RoverSimulationStates
RoverSimulationStates.ROVERSTATE_SIMULATION_UNDEFINED = 0;
RoverSimulationStates.ROVERSTATE_SIMULATION_NOTRUNNING = 1;
RoverSimulationStates.ROVERSTATE_SIMULATION_RUNNING = 2;


global NodeStates
NodeStates.NODESTATE_UNDEFINED = 0;
NodeStates.NODESTATE_BOOTING = 1;
NodeStates.NODESTATE_RUNNING = 2;
NodeStates.NODESTATE_SEARCHING_FOR_RECHARGE_FACILITY = 3;
NodeStates.NODESTATE_ACQUIRING_TARGET = 4;


global PowerStates
PowerStates.POWERSTATE_UNDEFINED = 0;
PowerStates.POWERSTATE_NORMAL = 1;
PowerStates.POWERSTATE_STANDBY = 2;
PowerStates.POWERSTATE_CHANGINGACTIVEBATTERY = 3;
PowerStates.POWERSTATE_REQUIRERECHARGE = 4;
PowerStates.POWERSTATE_EMERGENCY = 5;


global EStopStates
EStopStates.ESTOP_UNDEFINED = 0;
EStopStates.ESTOP_DISACTIVATED = 1;
EStopStates.ESTOP_ACTIVATED = 2;


global TaskStates
TaskStates.TASKSTATE_UNDEFINED = 0;
TaskStates.TASKSTATE_NODATA = 1;
TaskStates.TASKSTATE_INITIALIZING = 2;
TaskStates.TASKSTATE_RUNNING = 3;
TaskStates.TASKSTATE_STOPPED = 4;


global SignalState
SignalState.SIGNALSTATE_UNDEFINED = 0;
SignalState.SIGNALSTATE_INVALID = 1;
SignalState.SIGNALSTATE_INITIALIZING = 2;
SignalState.SIGNALSTATE_UPDATED = 3;
SignalState.SIGNALSTATE_EXTRAPOLATED = 4;
SignalState.SIGNALSTATE_HOLD = 5;
SignalState.SIGNALSTATE_CALIBRATING = 6;










global SignalClass
SignalClass.SIGNALCLASS_UNDEFINED = 0;
SignalClass.SIGNALCLASS_SENSORSIGNAL = 1;
SignalClass.SIGNALCLASS_TIMEDSIGNAL = 2;
SignalClass.SIGNALCLASS_PROCESSEDSIGNAL = 3;
SignalClass.SIGNALCLASS_INPUTSIGNAL = 4;
SignalClass.SIGNALCLASS_POSESIGNAL = 5;


global SignalType
SignalType.SIGNALTYPE_UNDEFINED = 0;
SignalType.SIGNALTYPE_ACCELERATION = 1;
SignalType.SIGNALTYPE_ROTATION_RATE = 2;
SignalType.SIGNALTYPE_MAGNETIC_FIELD = 3;
SignalType.SIGNALTYPE_TEMPERATURE = 4;
SignalType.SIGNALTYPE_DISTANCE = 5;
SignalType.SIGNALTYPE_ANGLE = 6;
SignalType.SIGNALTYPE_VELOCITY = 7;
SignalType.SIGNALTYPE_TICKSPEED = 8;
SignalType.SIGNALTYPE_UNITLESS = 255;


global LEDPixelMode
LEDPixelMode.LEDPIXELMODE_NONE = 0;
LEDPixelMode.LEDPIXELMODE_NORMAL = 1;
LEDPixelMode.LEDPIXELMODE_WARN = 2;
LEDPixelMode.LEDPIXELMODE_ERROR = 3;
LEDPixelMode.LEDPIXELMODE_COLORSELECT = 4;
LEDPixelMode.LEDPIXELMODE_FOCUS = 5;


global LEDPixelColor
LEDPixelColor.LEDPIXELCOLOR_OFF = 0;
LEDPixelColor.LEDPIXELCOLOR_RED = 1;
LEDPixelColor.LEDPIXELCOLOR_GREEN = 2;
LEDPixelColor.LEDPIXELCOLOR_BLUE = 3;
LEDPixelColor.LEDPIXELCOLOR_WHITE = 4;


global SQLCommandType
SQLCommandType.SQLCOMMANDTYPE_UNKNOWN = 0;
SQLCommandType.SQLCOMMANDTYPE_DATADEFINITION = 1;
SQLCommandType.SQLCOMMANDTYPE_DATAMANIPULATION = 2;
SQLCommandType.SQLCOMMANDTYPE_DATAQUERY = 3;




