#TAG: Start Message Definitions  ALL TEXT UNTIL TAG: End IS AUTO GENERATED
FINDTARGET_ID = 0XAB34
CONFIGURE_SHIELD_ID = 0XAB33
SET_DIO_PORT_DEFAULTVALUE_ID = 0XAB32
HEARTBEAT_ID = 0XAB31
ARM_STATUS_ID = 0XAB30
TUNE_CONTROLGROUP_ID = 0XAB29
SETUP_CONTROLGROUP_ID = 0XAB28
ARM_COMMAND_ID = 0XAB27
ARMCONTROL_ID = 0XAB26
FIRMWAREVERSION_ID = 0XAB25
GET_ANA_PORT_ID = 0XAB20
GET_DIO_PORT_ID = 0XAB19
SET_DIO_PORT_ID = 0XAB18
MODE_ID = 0XAB17
CONFIGURE_DIO_PORT_ID = 0XAB16
TESTMESSAGECOMMAND_ID = 0XAB15
TESTMESSAGECOUNTER_ID = 0XAB14
DEVICE_ID = 0XAB13
DIAGNOSTIC_ID = 0XAB12
RESOURCE_ID = 0XAB11
REMOTECONTROL_ID = 0XAB10
USERMESSAGE_ID = 0XAB01
#TAG: End Message Definitions
 
#Diagnostic Definitions
LEVEL1 = 1
LEVEL2 = 2
LEVEL3 = 3
LEVEL4 = 4
 
#Field 1: System
ROVER = 1
GROUND_STATION = 5
REMOTE_CONTROL = 7
 
#Field 2: Subsystem
ENTIRE_SYSTEM = 0
ROBOT_CONTROLLER = 1
 
#Field 3: Component
ENTIRE_SUBSYSTEM = 0
CONTROLLER_NODE = 1
DIAGNOSTIC_NODE = 2
NAVIGATION_NODE = 3
MAPPING_NODE = 7
EVOLUTION_NODE = 8
TARGETING_NODE = 9
TIMING_NODE = 10
VISION_NODE = 11
GPIO_NODE = 12
COMMUNICATION_NODE = 13
DYNAMICS_NODE = 14
 
#Field 4: Diagnostic Type
NOERROR = 0
ELECTRICAL = 1
SOFTWARE = 2
COMMUNICATIONS = 3
SENSORS = 4
ACTUATORS = 5
DATA_STORAGE = 6
REMOTE_CONTROL = 7
GENERAL_ERROR = 9
 
#Field 5: Level
DEBUG = 0  #This Level is solely for development/debugging only.
INFO = 1 #This Level is purely for informational use only.
NOTICE = 2  #This Level is a higher form of information and does not imply that anything is wrong.
WARN = 3  #This Level implies that a program is not running as expected, but may continue to operate in a diminished capacity.
ERROR = 4 #This Level implies that a program will not initialize or some other kind of crash.
FATAL = 5  #This Level implies that a program has failed so bad it can cause injury to itself or others.
 
#Field 6: Diagnostic_Message
NOERROR = 0  #Already defined above, just leaving here for completeness.
INITIALIZING = 1
INITIALIZING_ERROR = 2
DROPPING_PACKETS = 4
MISSING_HEARTBEATS = 5
DEVICE_NOT_AVAILABLE = 6
ROVER_ARMED = 7
ROVER_DISARMED = 8
TEMPERATURE_HIGH = 9
TEMPERATURE_LOW = 10
DIAGNOSTIC_PASSED = 11
DIAGNOSTIC_FAILED = 12
RESOURCE_LEAK = 13
HIGH_RESOURCE_USAGE = 14
 
#Armed States
ARMEDSTATUS_UNDEFINED = 0
ARMEDSTATUS_ARMED = 1
ARMEDSTATUS_DISARMED_CANNOTARM = 2
ARMEDSTATUS_DISARMED = 3
ARMEDSTATUS_DISARMING = 4
ARMEDSTATUS_ARMING = 5
 
#Armed Commands
ARMEDCOMMAND_UNDEFINED = 0
ARMEDCOMMAND_ARM = 1
ARMEDCOMMAND_DISARM = 2
 
#Board Types
BOARDTYPE_UNDEFINED = 0
BOARDTYPE_ARDUINOUNO = 1
BOARDTYPE_ARDUINOMEGA = 2
 
#Shield Types
SHIELDTYPE_UNDEFINED = 0
SHIELDTYPE_SERVOSHIELD = 1
SHIELDTYPE_LCDSHIELD = 2
SHIELDTYPE_RELAYSHIELD = 3
