//DO NOT EDIT THIS FILE.  IT IS MAINTAINED THROUGH EROS.

#ifndef __EROS_DEFINITIONS_INCLUDED__   
#define __EROS_DEFINITIONS_INCLUDED__
//Start: Message Definitions
#define StopMovement_ID 0xab27
#define StopMovement_ID 0xab27
#define ArmControl_ID 0xab26
#define FirmwareVersion_ID 0xab25
#define Get_DIO_PortB_ID 0xab24
#define Get_DIO_PortA_ID 0xab23
#define Set_DIO_PortB_ID 0xab22
#define Configure_DIO_PortB_ID 0xab21
#define Get_ANA_PortB_ID 0xab20
#define Get_ANA_PortA_ID 0xab19
#define Set_DIO_PortA_ID 0xab18
#define Mode_ID 0xab17
#define Configure_DIO_PortA_ID 0xab16
#define TestMessageCommand_ID 0xab15
#define TestMessageCounter_ID 0xab14
#define Device_ID 0xab13
#define Diagnostic_ID 0xab12
#define Diagnostic_ID 0xab12
#define Resource_ID 0xab11
#define RemoteControl_ID 0xab10
#define StopMovement_ID 0xab27
#define StopMovement_ID 0xab27
#define ArmControl_ID 0xab26
#define FirmwareVersion_ID 0xab25
#define Get_DIO_PortB_ID 0xab24
#define Get_DIO_PortA_ID 0xab23
#define Set_DIO_PortB_ID 0xab22
#define Configure_DIO_PortB_ID 0xab21
#define Get_ANA_PortB_ID 0xab20
#define Get_ANA_PortA_ID 0xab19
#define Set_DIO_PortA_ID 0xab18
#define Mode_ID 0xab17
#define Configure_DIO_PortA_ID 0xab16
#define TestMessageCommand_ID 0xab15
#define TestMessageCounter_ID 0xab14
#define Device_ID 0xab13
#define Diagnostic_ID 0xab12
#define Diagnostic_ID 0xab12
#define Resource_ID 0xab11
#define RemoteControl_ID 0xab10
//End: Message Definitions
//Diagnostic Definitions
#define LEVEL1 1
#define LEVEL2 2
#define LEVEL3 3
#define LEVEL4 4

//Field 1: System
#define ROVER 1
#define GROUND_STATION 5
#define REMOTE_CONTROL 7

//Field 2: Subsystem
#define ENTIRE_SYSTEM 0
#define ROBOT_CONTROLLER 1

//Field 3: Component
#define ENTIRE_SUBSYSTEM 0
#define CONTROLLER_NODE 1
#define DIAGNOSTIC_NODE 2
#define NAVIGATION_NODE 3
#define MAPPING_NODE 7
#define EVOLUTION_NODE 8
#define TARGETING_NODE 9
#define TIMING_NODE 10
#define VISION_NODE 11
#define GPIO_NODE 12
#define COMMUNICATION_NODE 13
#define DYNAMICS_NODE 14

//Field 4: Diagnostic Type
#define NOERROR 0
#define ELECTRICAL 1
#define SOFTWARE 2
#define COMMUNICATIONS 3
#define SENSORS 4
#define ACTUATORS 5
#define DATA_STORAGE 6
#define REMOTE_CONTROL 7
#define GENERAL_ERROR 9

//Field 5: Level
#define DEBUG 0  //This Level is solely for development/debugging only.
#define INFO 1 //This Level is purely for informational use only.
#define NOTICE 2  //This Level is a higher form of information and does not imply that anything is wrong.
#define WARN 3  //This Level implies that a program is not running as expected, but may continue to operate in a diminished capacity.
#define ERROR 4 //This Level implies that a program will not initialize or some other kind of crash.
#define FATAL 5  //This Level implies that a program has failed so bad it can cause injury to itself or others.

//Field 6: Diagnostic_Message
//#define NOERROR 0  Already defined above, just leaving here for completeness.
#define INITIALIZING 1
#define INITIALIZING_ERROR 2
#define DROPPING_PACKETS 4
#define MISSING_HEARTBEATS 5
#define DEVICE_NOT_AVAILABLE 6
#define ROVER_ARMED 7
#define ROVER_DISARMED 8
#define TEMPERATURE_HIGH 9
#define TEMPERATURE_LOW 10
#define DIAGNOSTIC_PASSED 11
#define DIAGNOSTIC_FAILED 12
#endif