// A list of all supported Device Types
#define DEVICETYPE_ARDUINOBOARD "ArduinoBoard"
#define DEVICETYPE_AUDIOAMPLIFIER "AudioAmplifier"
#define DEVICETYPE_BATTERY "Battery"
#define DEVICETYPE_COMPUTEMODULE "ComputeModule"
#define DEVICETYPE_CONTROLMODULE "ControlModule"
#define DEVICETYPE_GPIOHAT "GPIOHat"
#define DEVICETYPE_IMU "IMU"
#define DEVICETYPE_LCD "LCD"
#define DEVICETYPE_MICROPHONE "Microphone"
#define DEVICETYPE_SERVOHAT "ServoHat"
#define DEVICETYPE_TERMINALHAT "TerminalHat"