%***************AUTO-GENERATED.  DO NOT EDIT********************/
%***Created on:%2020-02-18 05:43:04.492622%***/
classdef PowerStates < uint8
	enumeration
		POWERSTATE_UNDEFINED_ (0)
		POWERSTATE_NORMAL_ (1)
		POWERSTATE_STANDBY_ (2)
		POWERSTATE_CHANGINGACTIVEBATTERY_ (3)
		POWERSTATE_REQUIRERECHARGE_ (4)
		POWERSTATE_EMERGENCY_ (5)
		POWERSTATE_CHARGING_ (6)
	end
end