%***************AUTO-GENERATED.  DO NOT EDIT********************/
%***Created on:%2020-02-18 05:43:04.492868%***/
classdef RoverCommand_SimulationControl < uint8
	enumeration
		ROVERCOMMAND_SIMULATIONCONTROL_UNDEFINED_ (0)
		ROVERCOMMAND_SIMULATIONCONTROL_RESETWORLD_ (1)
		ROVERCOMMAND_SIMULATIONCONTROL_STARTSIM_ (2)
		ROVERCOMMAND_SIMULATIONCONTROL_PAUSESIM_ (3)
	end
end