%***************AUTO-GENERATED.  DO NOT EDIT********************/
%***Created on:%2020-02-18 05:43:04.492457%***/
classdef RoverCommands < uint8
	enumeration
		ROVERCOMMAND_UNDEFINED_ (0)
		ROVERCOMMAND_BOOT_ (1)
		ROVERCOMMAND_NONE_ (2)
		ROVERCOMMAND_RUNDIAGNOSTIC_ (3)
		ROVERCOMMAND_SEARCHFOR_RECHARGE_FACILITY_ (4)
		ROVERCOMMAND_STOPSEARCHFOR_RECHARGE_FACILITY_ (5)
		ROVERCOMMAND_ACQUIRE_TARGET_ (6)
		ROVERCOMMAND_ARM_ (7)
		ROVERCOMMAND_DISARM_ (8)
		ROVERCOMMAND_CONFIGURE_ (9)
		ROVERCOMMAND_RUN_ (10)
		ROVERCOMMAND_STOPMOVEMENT_ (11)
		ROVERCOMMAND_DRIVECOMMAND_ (12)
		ROVERCOMMAND_RESET_ (13)
		ROVERCOMMAND_SETLOGLEVEL_ (14)
		ROVERCOMMAND_TASKCONTROL_ (15)
		ROVERCOMMAND_CALIBRATION_ (16)
		ROVERCOMMAND_GENERATESNAPSHOT_ (17)
		ROVERCOMMAND_SIMULATIONCCONTROL_ (18)
		ROVERCOMMAND_WAIT_ (254)
		ROVERCOMMAND_UNKNOWN_ (255)
	end
end