%***************AUTO-GENERATED.  DO NOT EDIT********************/
%***Created on:%2020-02-18 05:43:04.492776%***/
classdef RoverCommand_Calibration < uint8
	enumeration
		ROVERCOMMAND_CALIBRATION_UNDEFINED_ (0)
		ROVERCOMMAND_CALIBRATION_NONE_ (1)
		ROVERCOMMAND_CALIBRATION_MAGNETOMETER_ (2)
		ROVERCOMMAND_CALIBRATION_MOUNTINGANGLEOFFSET_ (3)
	end
end