%***************AUTO-GENERATED.  DO NOT EDIT********************/
%***Created on:%2020-02-18 05:43:04.492899%***/
classdef SignalClass < uint8
	enumeration
		SIGNALCLASS_UNDEFINED_ (0)
		SIGNALCLASS_SENSORSIGNAL_ (1)
		SIGNALCLASS_TIMEDSIGNAL_ (2)
		SIGNALCLASS_PROCESSEDSIGNAL_ (3)
		SIGNALCLASS_INPUTSIGNAL_ (4)
		SIGNALCLASS_POSESIGNAL_ (5)
		SIGNALCLASS_TRUTHSIGNAL_ (6)
	end
end