%***************AUTO-GENERATED.  DO NOT EDIT********************/
%***Created on:%2020-02-18 05:43:04.492937%***/
classdef SignalType < uint8
	enumeration
		SIGNALTYPE_UNDEFINED_ (0)
		SIGNALTYPE_ACCELERATION_ (1)
		SIGNALTYPE_ROTATION_RATE_ (2)
		SIGNALTYPE_MAGNETIC_FIELD_ (3)
		SIGNALTYPE_TEMPERATURE_ (4)
		SIGNALTYPE_DISTANCE_ (5)
		SIGNALTYPE_ANGLE_ (6)
		SIGNALTYPE_VELOCITY_ (7)
		SIGNALTYPE_TICKSPEED_ (8)
		SIGNALTYPE_FORCE_ (9)
		SIGNALTYPE_UNITLESS_ (255)
	end
end