%***************AUTO-GENERATED.  DO NOT EDIT********************/
%***Created on:%2020-02-18 05:43:04.492692%***/
classdef TaskStates < uint8
	enumeration
		TASKSTATE_UNDEFINED_ (0)
		TASKSTATE_START_ (1)
		TASKSTATE_INITIALIZING_ (2)
		TASKSTATE_INITIALIZED_ (3)
		TASKSTATE_LOADING_ (4)
		TASKSTATE_RUNNING_ (5)
		TASKSTATE_PAUSE_ (6)
		TASKSTATE_RESET_ (7)
		TASKSTATE_NODATA_ (253)
		TASKSTATE_FINISHED_ (254)
	end
end