@startuml
title "Device Window Class Diagram"
abstract WindowTable {
    
}
class DeviceWindow {
    -DeviceManager manager
}
class DeviceManager {
    -Device[] devices
}
DeviceWindow -> DeviceManager
class Device {

}
DeviceManager --* "*" Device
WindowTable <|-- DeviceWindow
@enduml