# This is a basic workflow to help you get started with Actions

name: BuildTest

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ US_1100_SetupBuildServerPipeline ]


  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest



    steps:
    - uses: actions/checkout@v1
      with:
        path: catkin_ws/src/eros
        
    - name: Add Pipeline Tools
      run: |
        sudo apt install tree
        echo $PWD
        echo ~
        tree -a
   
    - name: Install gTest
      run: |
        sudo apt -y install googletest

    - uses: ros-tooling/setup-ros@v0.3
      with:
        required-ros-distributions: noetic


    - name: Setup
      run: |
        echo $PWD
        tree
        python scripts/simple_setup.py
      #working-directory: catkin_ws/src/eros
    
    - name: Build Libraries & Binaries
      run: |
        cd ../../
        source /opt/ros/noetic/setup.bash
        catkin_make

    - name: Build Tests
      run: |
        source /opt/ros/noetic/setup.bash
        catkin_make tests
      #working-directory: catkin_ws

    - name: Run Tests
      run: |
        source /opt/ros/noetic/setup.bash
        catkin_make run_tests
      #working-directory: catkin_ws
    #- uses: ros-tooling/action-ros-ci@v0.2
    #  with:
    #    package-name: eros
    #    target-ros1-distro: noetic
