# This is a basic workflow to help you get started with Actions

name: BuildTest

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ US_1100_SetupBuildServerPipeline ]


  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
    - uses: ros-tooling/setup-ros@v0.3
      with:
        required-ros-distributions: noetic
    - uses: ros-tooling/action-ros-ci@v0.2
      with:
        package-name: eros
        target-ros1-distro: noetic
