# This is a basic workflow to help you get started with Actions

name: BuildTest

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ US_1100_SetupBuildServerPipeline ]


  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
      image: ubuntu:jammy

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: ros-tooling/setup-ros@v0.4
      with:
        required-ros-distributions: noetic
    - run: "source /opt/ros/noetic/setup.bash && rosnode --help"
