name: BuildTest

on:
  workflow_call:


jobs:
  BuildTest:
    runs-on: self-hosted

    steps:
    - name: Hack
      run: |
        sudo chown -R $USER:$USER ~/actions-runner/_work/eros
    - uses: actions/checkout@v1
      with:
        path: catkin_ws/src/eros
        
    - name: Add Pipeline Tools
      run: |
        sudo apt install tree
   
    - name: Setup
      run: |
        python scripts/simple_setup.py

    - name: Build Libraries & Binaries
      run: |
        cd ../../
        source /opt/ros/noetic/setup.bash
        rm -r -f build/ devel/
        catkin_make

    - name: Build Tests
      run: |
        cd ../../
        source /opt/ros/noetic/setup.bash
        catkin_make tests

    - name: Run Tests
      run: |
        cd ../../
        source /opt/ros/noetic/setup.bash
        catkin_make -j1 run_tests
        catkin_test_results build/test_results
      
    - name: Code Coverage
      run: |
        ./scripts/dev_tools.sh

    - name: Code Coverage Summary Report
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: coverage/coverage.xml
