name: BuildTest

on:
  workflow_call:

jobs:
  BuildTest:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v1
      with:
        path: catkin_ws/src/eros
  
    - name: Setup
      run: |
        python scripts/simple_setup.py

      - name: Process Diagrams
        run: |
            mkdir output
            java -jar plantuml.jar -v -tsvg -r -o "${{ github.workspace }}/output" "doc*/**.puml"
      - name: Display Diagrams
        run: pwd && ls output
      - name: Commit Diagrams
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m ":rocket: adding generated diagrams" || exit 0
      - name: Push Diagrams
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Libraries & Binaries
      run: |
        cd ../../
        source /opt/ros/noetic/setup.bash
        rm -r -f build/ devel/
        catkin_make

    - name: Build Tests
      run: |
        cd ../../
        source /opt/ros/noetic/setup.bash
        catkin_make tests

    - name: Run Tests
      run: |
        cd ../../
        source /opt/ros/noetic/setup.bash
        catkin_make -j1 run_tests
        catkin_test_results build/test_results
      
    - name: Code Coverage
      run: |
        ./scripts/dev_tools.sh

    - name: Code Coverage Summary Report
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: coverage/coverage.xml
        badge: true
