# This is a basic workflow to help you get started with Actions

name: BuildTest

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ US_1100_SetupBuildServerPipeline ]


  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
    - name: Install gTest
      run: |
        set -e
        sudo apt-get install -y libgtest-dev
        cd /usr/src/gtest/
        sudo mkdir build
        cd build
        sudo cmake ..
        sudo make
        sudo make install
        
    - uses: ros-tooling/setup-ros@v0.3
      with:
        required-ros-distributions: noetic


    - name: Setup
      run: |
        echo "$PWD"
        mkdir -p catkin_ws/src/ && cd catkin_ws/src/
        git clone https://github.com/dgitz/eros.git
        cd eros
        python scripts/simple_setup.py
    
    - name: Build Libraries & Binaries
      run: |
        echo "$PWD"
        source /opt/ros/noetic/setup.bash
        catkin_make
      working-directory: catkin_ws

    - name: Build Tests
      run: |
        source /opt/ros/noetic/setup.bash
        catkin_make tests
      working-directory: catkin_ws

    - name: Run Tests
      run: |
        source /opt/ros/noetic/setup.bash
        catkin_make run_tests
      working-directory: catkin_ws
    #- uses: ros-tooling/action-ros-ci@v0.2
    #  with:
    #    package-name: eros
    #    target-ros1-distro: noetic
