name: Release

on:
  push:
    branches: [ master,noetic-devel ]

jobs:
  call_BuildTest:
    uses: ./.github/workflows/buildtest.yml
    
  #call_Documentation: # Resolve during AB#1362
    #needs: call_BuildTest
    #uses: ./.github/workflows/documentation.yml