name: Release

on:
  push:
    #branches: [ master ]

jobs:
  call_BuildTest:
    uses: ./.github/workflows/buildtest.yml
    
  call_Documentation:
    needs: call_BuildTest
    uses: ./.github/workflows/documentation.yml